### ISSUE TITLE
devices.capabilities.toggle is not supported

### ISSUE THREAD

**Issue by DuBass858** [lasthead0/yandex2mqtt#1]
Is it planned to support the toggle?

**Comment by lasthead0** [comment]
i did not check specially this capability. I will check and report here.

**Comment by DuBass858** [comment]
If i can help you, please let me know

**Comment by lasthead0** [comment]
I found problem and fix it, and I made some checks. So toggle have to work now. I made packages upgrade and some code changes, so i recommend to save config file and make full reinstall y2m.
