### ISSUE TITLE
Как получить показания из датчика с несколькими сенсорами

### ISSUE THREAD

**Issue by alex1iam** [lasthead0/yandex2mqtt#10]
Есть такой блок датчика освещенности-влажности-температуры:
        {
            id: 'id_device_12',
            name: 'Сенсор',
            room: 'Кухня',
            type: 'devices.types.sensor',
            mqtt: [
                 {
                    instance: 'humidity',
                    state: 'zigbee2mqtt/0x804b50fffe0abc8b'
                },
            ],
            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance:'humidity',
                        unit:'unit.percent',
                    }
                },

            ]
        },
Но в результате показывается 0 для влажности, возможно из-за того, что в топик приходят значения для нескольких свойств датчика: payload '{"humidity":66.3,"illuminance":16722,"illuminance_lux":47,"temperature":24.41}' и программа не может выделить определенный

**Comment by lasthead0** [comment]
Вот например так температура и влажность
```
/* LvR Weather */
        {
            id: 'lvr-001-weather',
            name: 'В гостиной',
            room: 'Гостиная',
            type: 'devices.types.sensor',
            allowedUsers: ['2'],
            mqtt: [
                {
                    instance: 'temperature',
                    state: '/yandex/sensors/LvR_001_Weather/temperature',
                },
                {
                    instance: 'humidity',
                    state: '/yandex/sensors/LvR_001_Weather/humidity',
                },
            ],
            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius',
                    },
                },
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'humidity',
                        unit: 'unit.percent',
                    },
                },
            ],
        },
```

**Comment by alex1iam** [comment]
ну, у меня вроде так же, почему в яндекс прилетает 0

**Comment by lasthead0** [comment]
Причин может быть множество. В конце readme есть описание нескольких ошибок. Так же причиной может быть, то, что вы используете в качестве топиков, топики z2m. Может не правильно написан топик. Может ещё что-то.

**Comment by alex1iam** [comment]
Все, можно закрывать. Решил проблему.

**Comment by alex1iam** [comment]
спасибо
