### ISSUE TITLE
Датчик протечки в топик выдает true и false, из-за чего не работает связка с УД яндекса

### ISSUE THREAD

**Issue by alex1iam** [lasthead0/yandex2mqtt#11]
Есть датчик протечки от акара, который выдает примерно вот такой топик: 'zigbee2mqtt/0x00158d0004058187/water_leak', payload 'false' (или true, когда протечка). 
есть вот такой конфиг y2m:
//_______________Датчик протечки в ванной______________//
        {
            id: 'id_device_14',
            name: 'Датчик протечки',
            room: 'Ванная',
            type: 'devices.types.sensor',
            mqtt: [   {  
                   instance: 'water_leak',
                    state: 'zigbee2mqtt/0x00158d0004058187/water_leak'    },      ],
            properties: [   {
                    type: 'devices.properties.event',
                    retrievable: true,
                    reportable: true,
                    parameters: {
                        instance:'water_leak',
                          events:    [    {
                           value: true,    },
                    {      
                          value: false,    },      ]
                     }         },       ],      },
    //__________Конец Датчик протечки в ванной_______//

В такой конфигурации y2m запускается нормально, но при добавлении нового устройства уд яндекса говорит, что не удалось обновить список устройств, но уже добавленные работают нормально. 
Если, например, в value поместить 'leak' и 'dry' (как это описывается в названиях функции устройств протечки в справке яндекса), а потом сделать маппинг в конфиге, устройство нормально добавляется в уд яндекса, но естественно ничего не приходит, так как в топике true, а не leak. Маппинг на true-true не помогает

**Comment by lasthead0** [comment]
Нужно сделать по аналогии как в примере в README.
```
{
        id: 'haw-001-motion',
        name: 'Движение',
        room: 'Коридор',
        type: 'devices.types.sensor',
        allowedUsers: ['2'],
        mqtt: [
            {
                instance: 'motion',
                state: '/yandex/sensors/HaW_001_Motion/motion',
            },
        ],
        valueMapping: [
            {
                type: 'event',
                mapping: [['not_detected', 'detected'], ['false', 'true']], // [yandex, mqtt]
            },
        ],
        properties: [
            {
                type: 'devices.properties.event',
                retrievable: true,
                reportable: true,
                parameters: {
                    instance: 'motion',
                    events: [{
                        value: 'detected'
                    },
                    {
                        value: 'not_detected'
                    }]
                },
            },
        ],
    },
```

**Comment by alex1iam** [comment]
вот в том то и дело. если я делаю такой конфиг
//_______________Датчик протечки в ванной______________//
        {
            id: 'id_device_14',
            name: 'Датчик протечки',
            room: 'Ванная',
            type: 'devices.types.sensor',
            mqtt: [
                 {
                    instance: 'water_leak',
                    state: 'zigbee2mqtt/0x00158d0004058187/water_leak'
                },
                  ],
        valueMapping: [
            {
                type: 'event',
                mapping: [[false, true], ['false', 'true']], // [yandex, mqtt]
            },
        ],
            properties: [
                {
                    type: 'devices.properties.event',
                    retrievable: true,
                    reportable: true,
                    parameters: {
                        instance:'water_leak',
                          events:
                        [
                    {
                           value: 'true',
                    },
                    {
                           value: 'false',
                    },
                       ]
                     }
                },

            ],
        },
    //__________Конец Датчик протечки в ванной_________//

то яндекс уд говорит, что новых устройств не обнаружено

**Comment by lasthead0** [comment]
Внимательно прочтите что должно быть в блоке `events` у `water_leak`. https://dialogs.yandex.ru/docs/smart-home/doc/concepts/event-instance.html#event-instance__water_leak

**Comment by alex1iam** [comment]
да читал я.  проблема в том, что у меня в топик mqtt выкидывается не dry/leak, а true/false

**Comment by lasthead0** [comment]
Тот конфиг, который Вы прислали - не правильный. Это первое что нужно исправить.

**Comment by lasthead0** [comment]
dry/leak берётся из valueMapping, который вы настроили, т.е. true/false будут превращаться в dry/leak и наоборот. В README об это написано.
Правда valueMapping тоже настроен не верно. т.к. mqtt это брокер СООБЩЕНИЙ, это значит что все значения в топиках - это текст. А это значить, что значения `true/false` должны быть представлены в виде текста, т.е. `'true'/'false'`. А значит mapping должен выглядеть так `mapping: [['dry', 'leak'], ['false', 'true']]`.

**Comment by alex1iam** [comment]
Все, я понял ошибку. Я считал, что value берутся из топика
спасибо
