### ISSUE TITLE
Fix updating from MQTT

### ISSUE THREAD

**Issue by DoroganovV** [lasthead0/yandex2mqtt#2]
Приветствую, при использовании обнаружил ошибку в файле app.js, строка 90
const {instance, state: topic} = mqtt;
надо 
const {instance, stat: topic} = mqtt;
иначе не работает подписка на обновления из шины MQTT

**Comment by lasthead0** [comment]
Зависит от файла конфигурации. В оригинальном проекте топик обновления был под именем stat - такого слова в английской, так сказать, нет, поэтому я переименовал в state. Возможно, что-то сломалось.
Сейчас работаю над некоторым обновлением, связанным с обновлением состоянием устройств в навыках Яндекс. Проверю, если ошибка будет - решу.

**Comment by DoroganovV** [comment]
Ну да, согласен, по факту в конфиге другое название, может чтобы не путаться так сделал автор.
