### ISSUE TITLE
Не работает с wirenboard 6 прошивка 2307

### ISSUE THREAD

**Issue by 1stat** [lasthead0/yandex2mqtt#20]
Не могли бы помочь пожалуйста, все работало. Обновился и поломалось. Собирал уже раз 10 по инструкции. Устройство корректно добавились в Яндекс, но управлять ими не получается. Выдает ошибку (что то пошло не так)

**Comment by lasthead0** [comment]
День добрый. К сожалению, то что Вы написали никак не поможет понять проблему и помочь её решить. Нужно смотреть логи y2m, Яндекса. Конфиг нужно смотреть.

**Comment by 1stat** [comment]
А куда логи от y2m падают?

**Comment by 1stat** [comment]
`module.exports = {

    mqtt: {
        host: 'localhost',
        port: 1883,
        user: '',
        password: ''
    },

    https: {
	privateKey: '/etc/letsencrypt/live/1111111111.ru/privkey.pem',
        certificate: '/etc/letsencrypt/live/11111111111.ru/fullchain.pem',
        port: 443,
    },

    clients: [
    {
        id: '1',
        name: 'Yandex',
        clientId: '123123135',
        clientSecret: '123123123',
        isTrusted: false
        },
    ],

    users: [{
            id: '1',
            username: '123123',
            password: '123123',
            name: 'Administrator'
        },
    ],

    devices: [
//_______________Подсветка детская_____________//
        {
			id: 'light-001-kid',
            name: 'Подсветка в детской',
            room: 'Детская',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_roman/controls/Подсветка в детской/on',
                    stat: '/devices/light_roman/controls/Подсветка в детской'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//_______________Подсветка детская_____________//
//_______________Бра Роман_____________//
        {
			id: 'bra-001-kid',
            name: 'Бра в детской',
            room: 'Детская',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_roman/controls/Бра в детской/on',
                    stat: '/devices/light_roman/controls/Бра в детской'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//_______________Бра Роман_____________//
//_______________Свет компьютер_____________//
        {
			id: 'lamp-001-pc',
            name: 'Подсветка колонны',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Подсветка колонны/on',
                    stat: '/devices/light_bedroom/controls/Подсветка колонны'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//_______________Свет компьютер_____________//
//_______________Бра макияжная зона_____________//
        {
			id: 'bra-001-cosmetic',
            name: 'Свет над макияжной зоной',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Макияжная зона/on',
                    stat: '/devices/light_bedroom/controls/Макияжная зона'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//_______________Бра макияжная зона_____________//
//_______________Бра справа_____________//
        {
			id: 'bra-001-r',
            name: 'Бра справа',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Бра Кристина/on',
                    stat: '/devices/light_bedroom/controls/Бра Кристина'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Бра справа__________//
//_______________Бра слева______________//
        {
			id: 'bra-001-l',
            name: 'Бра слева',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Бра Святослав/on',
                    stat: '/devices/light_bedroom/controls/Бра Святослав'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Бра слева__________//
//_______________Свет в гардеробной______________//
        {
			id: 'light-001-gb',
            name: 'Свет в гардеробной',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Свет в гардеробной/on',
                    stat: '/devices/light_bedroom/controls/Свет в гардеробной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Свет в гардеробной__________//
//_______________Свет фартук______________//
        {
			id: 'light-001-kit',
            name: 'Свет на кухне',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_lounge/controls/Свет на кухне/on',
                    stat: '/devices/light_lounge/controls/Свет на кухне'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Свет фартук__________//
//_______________Свет в серверной______________//
        {
			id: 'light-001-serv',
            name: 'Свет в серверной',
            room: 'Серверная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/server_room/controls/Свет в серверной/on',
                    stat: '/devices/server_room/controls/Свет в серверной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Свет в серверной__________//
//_______________Свет в коридоре______________//
        {
			id: 'light-001-hall',
            name: 'Свет в коридоре',
            room: 'Коридор',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_hall/controls/Свет в коридоре/on',
                    stat: '/devices/light_hall/controls/Свет в коридоре'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Свет в коридоре__________//
//_______________Ванная бра______________//
        {
			id: 'bra-001-bath',
            name: 'Бра в ванной',
            room: 'Ванная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bathroom/controls/Бра в ванной/on',
                    stat: '/devices/light_bathroom/controls/Бра в ванной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Ванная бра__________//
//_______________Ванная свет основной______________//
        {
			id: 'light-001-bath',
            name: 'Свет в ванной',
            room: 'Ванная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bathroom/controls/Свет в ванной/on',
                    stat: '/devices/light_bathroom/controls/Свет в ванной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Ванная свет основной__________//

//_______________Дежурный свет______________//
        {
			id: 'light-001-dej',
            name: 'Дежурный свет',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_lounge/controls/Дежурный свет/on',
                    stat: '/devices/light_lounge/controls/Дежурный свет'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//__________Дежурный свет__________//
//_______________С/У свет______________//
        {
			id: 'light-001-toul',
            name: 'Свет в туалете',
            room: 'Туалет',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_lavatory/controls/Свет в туалете/on',
                    stat: '/devices/light_lavatory/controls/Свет в туалете'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },
//_______________С/У свет______________//
  //_______________Свет в гостиной______________//
        {
			id: 'light-001-lounge',
            name: 'Свет в гостиной',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_lounge/controls/Свет в гостиной/on',
                    stat: '/devices/light_lounge/controls/Свет в гостиной'
                },              
                {
                    type: 'brightness',
                    set: '/devices/light_lounge/controls/Яркость в гостиной/on',
                    stat: '/devices/light_lounge/controls/Яркость в гостиной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Свет в гостиной______________//
//_______________Свет над столом______________//
        {
			id: 'light-001-table',
            name: 'Свет над столом',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_lounge/controls/Свет над столом/on',
                    stat: '/devices/light_lounge/controls/Свет над столом'
                },              
                {
                    type: 'brightness',
                    set: '/devices/light_lounge/controls/Яркость над столом/on',
                    stat: '/devices/light_lounge/controls/Яркость над столом'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Свет над столом______________//
//_______________Свет в спальне______________//
        {
			id: 'light-001-bed',
            name: 'Свет в спальне',
            room: 'Спальня',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_bedroom/controls/Свет в спальне/on',
                    stat: '/devices/light_bedroom/controls/Свет в спальне'
                },              
                {
                    type: 'brightness',
                    set: '/devices/light_bedroom/controls/Яркость в спальне/on',
                    stat: '/devices/light_bedroom/controls/Яркость в спальне'
                },
            ],
			valueMapping: [
				{
					type: 'on_off',
					mapping: [[false, true], [0, 1]], // [yandex, mqtt]
				},
			],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Свет в спальне______________//
//_______________Свет в детской______________//
        {
			id: 'lamp-001-kids',
            name: 'Свет в детской',
            room: 'Детская',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_roman/controls/Свет в детской/on',
                    stat: '/devices/light_roman/controls/Свет в детской'
                },              
                {
                    type: 'brightness',
                    set: '/devices/light_roman/controls/Яркость в детской/on',
                    stat: '/devices/light_roman/controls/Яркость в детской'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Свет в детской______________//
//_______________Температура в гостиной______________//
        {
			id: 'temp-001-lounge',
            name: 'Температура в гостиной',
            room: 'Гостиная',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'temperature',
                    stat: '/devices/Temper/controls/Гостиная'
                },
				],
       

            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    state: {
                         instance: 'temperature',
                        value: 0
                    },
					parameters:{ 
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius'
                               }
                },
            ]
        },

//_______________Температура в гостиной______________//
//_______________Температура в спальне______________//
        {
			id: 'temp-001-bed',
            name: 'Температура в спальне',
            room: 'Спальня',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'temperature',
                    stat: '/devices/Temper/controls/Спальня'
                },
				],
       

            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    state: {
                         instance: 'temperature',
                        value: 0
                    },
					parameters:{ 
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius'
                               }
                },
            ]
        },

//_______________Температура в спальне______________//        
//_______________Температура в серверной______________//
        {
			id: 'temp-001-serv',
            name: 'Температура в серверной',
            room: 'Серверная',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'temperature',
                    stat: '/devices/Temper/controls/Серверная'
                },
				],
       

            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    state: {
                         instance: 'temperature',
                        value: 0
                    },
					parameters:{ 
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius'
                               }
                },
            ]
        },

//_______________Температура в серверной______________//
//_______________Температура на улице______________//
        {
			id: 'temp-001-out',
            name: 'Температура на улице',
            room: 'Улица',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'temperature',
                    stat: '	/devices/Temper/controls/Улица'
                },
				],
       

            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    state: {
                         instance: 'temperature',
                        value: 0
                    },
					parameters:{ 
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius'
                               }
                },
            ]
        },

//_______________Температура на улице______________//
//_______________Температура в детской______________//
        {
			id: 'temp-001-kid',
            name: 'Температура в детской',
            room: 'Детская',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'temperature',
                    stat: '	/devices/Temper/controls/Роман'
                },
				],
       

            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    state: {
                         instance: 'temperature',
                        value: 0
                    },
					parameters:{ 
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius'
                               }
                },
            ]
        },

//_______________Температура в детской______________//
//_______________Вытяжка в С/У______________//
        {
			id: 'blow-001-toul',
            name: 'Вытяжка в туалете',
            room: 'Туалет',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/inside_blowers/controls/Вытяжка в туалете/on',
                    stat: '/devices/inside_blowers/controls/Вытяжка в туалете'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________Вытяжка в С/У______________// 
//_______________Вытяжка в ванной______________//
        {
			id: 'blow-001-bath',
            name: 'Вытяжка в ванной',
            room: 'Ванная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/inside_blowers/controls/Вытяжка в ванной/on',
                    stat: '/devices/inside_blowers/controls/Вытяжка в ванной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________Вытяжка в ванной______________// 
//_______________Вода______________//
        {
			id: 'water-001-pc',
            name: 'Вода',
            room: 'Туалет',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/state_water/controls/Включена-Отключена/on',
                    stat: '/devices/state_water/controls/Включена-Отключена'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________Вода______________//
//_______________Сигнализация______________//
        {
			id: 'signal-001-pc',
            name: 'Сигнализация',
            room: 'Серверная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/security_dev/controls/Ночной режим/on',
                    stat: '/devices/security_dev/controls/Ночной режим'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________Сигнализация______________//

//_______________Гирлянда______________//
        {
			id: 'ng-001-lounge',
            name: 'Гирлянда',
            room: 'Гостиная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/light_party/controls/Гирлянда в гостиной/on',
                    stat: '/devices/light_party/controls/Гирлянда в гостиной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________Гирлянда______________//    
//_______________Вентиляция в гостиной______________//
        {
			id: 'vent-001-lounge',
            name: 'Вентиляция в гостиной',
            room: 'Гостиная',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/outside_blowers/controls/Вентиляция в гостиной/on',
                    stat: '/devices/outside_blowers/controls/Вентиляция в гостиной'
                },              
                {
                    type: 'brightness',
                    set: '/devices/outside_blowers/controls/Мощность вентиляции в гостиной/on',
                    stat: '/devices/outside_blowers/controls/Мощность вентиляции в гостиной'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Вентиляция в гостиной____________// 
//_______________Вентиляция в спальне______________//
        {
			id: 'vent-001-bed',
            name: 'Вентиляция в спальне',
            room: 'Спальня',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/outside_blowers/controls/Вентиляция в спальне/on',
                    stat: '/devices/outside_blowers/controls/Вентиляция в спальне'
                },              
                {
                    type: 'brightness',
                    set: '/devices/outside_blowers/controls/Мощность вентиляции в спальне/on',
                    stat: '/devices/outside_blowers/controls/Мощность вентиляции в спальне'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Вентиляция в спальне____________//
//_______________Вентиляция в детской______________//
        {
			id: 'vent-001-kid',
            name: 'Вентиляция в детской',
            room: 'Детская',
            type: 'devices.types.other',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/outside_blowers/controls/Вентиляция в детской/on',
                    stat: '/devices/outside_blowers/controls/Вентиляция в детской'
                },              
                {
                    type: 'brightness',
                    set: '/devices/outside_blowers/controls/Мощность вентиляции в детской/on',
                    stat: '/devices/outside_blowers/controls/Мощность вентиляции в детской'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
                {
                    type: 'devices.capabilities.range',
                    retrievable: true,

                    parameters: {
                        instance: 'brightness',
                        unit: 'unit.percent',
                        range: {
                            min: 0,
                            max: 100,
                            precision: 1
                        }
                    },
                    state: {
                        instance: 'brightness',
                        value: 0,
                    },
                },
            ]
        },
//_______________Вентиляция в детской____________//  
//_______________RGB TV______________//
        {
			id: 'rgb-001-tv',
            name: 'Цвет тв',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
				{
                    type: 'on',
                    set: '/devices/light_RGB/controls/Подсветка телевизора',
                    stat: '/devices/light_RGB/controls/Подсветка телевизора'
                },     
				{
                    type: 'rgb',
                    set: '/devices/light_RGB/controls/Цвет над телевизором/on',
                    stat: '/devices/light_RGB/controls/Цвет над телевизором/'
                },     				
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
				{
                    type: 'devices.capabilities.color_setting',
                    retrievable: true,
                    parameters: {
                        color_model: 'rgb',
                    },
                    state: {
                        instance: 'rgb',
                        value: 0,
                    },
                },
            ]
        },
//_______________RGB TV____________//   
//_______________RGB KITCHEN______________//
        {
			id: 'rgb-001-kit',
            name: 'Цвет фартука',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
				{
                    type: 'on',
                    set: '/devices/light_RGB/controls/Подсветка фартука/on',
                    stat: '/devices/light_RGB/controls/Подсветка фартука'
                },     
				{
                    type: 'rgb',
                    set: '/devices/light_RGB/controls/Цвет над фартуком/on',
                    stat: '/devices/light_RGB/controls/Цвет над фартуком/'
                },     				
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
				{
                    type: 'devices.capabilities.color_setting',
                    retrievable: true,
                    parameters: {
                        color_model: 'rgb',
                    },
                    state: {
                        instance: 'rgb',
                        value: 0,
                    },
                },
            ]
        },
//_______________RGB KITCHEN______________// 
//_______________RGB ALL______________//
        {
			id: 'rgb-001-all',
            name: 'Цвет',
            room: 'Гостиная',
            type: 'devices.types.light',
			allowedUsers: ['1'],
            mqtt: [
				{
                    type: 'on',
                    set: '/devices/light_lounge/controls/Подсветка в гостиной/on',
                    stat: '/devices/light_lounge/controls/Подсветка в гостиной'
                },       
				{
                    type: 'rgb',
                    set: '/devices/light_lounge/controls/Цвет/on',
                    stat: '/devices/light_lounge/controls/Цвет'
                },     				
            ],
            capabilities: [
              {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
              },
			  {
                    type: 'devices.capabilities.color_setting',
                    retrievable: true,
                    parameters: {
                        color_model: 'rgb',
                    },
                    state: {
                        instance: 'rgb',
                        value: 0,
                    },
                },
            ]
        },
//_______________RGB ALL____________//
//_______________TOWEL______________//
        {
			id: 'towel-001-pc',
            name: 'Полотенцесушитель',
            room: 'Ванная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/towel/controls/Включен на 8ч/on',
                    stat: '/devices/towel/controls/Включен на 8ч'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________TOWEL______________//  
//_______________ELSWITCH______________//
        {
			id: 'el-001-pc',
            name: 'Электричество',
            room: 'Серверная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/elswitch/controls/Включено-Выключено/on',
                    stat: '/devices/elswitch/controls/Включено-Выключено'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________ELSWICH______________//  
//_______________hotreg______________//
        {
			id: 'termreg-001-pc',
            name: 'Терморегуляторы',
            room: 'Серверная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/state_heating/controls/Состояние терморегуляторов/on',
                    stat: '/devices/state_heating/controls/Состояние терморегуляторов'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________hotreg______________//  
//_______________hot_on_off______________//
        {
			id: 'hot-001-pc',
            name: 'Отопление',
            room: 'Серверная',
            type: 'devices.types.switch',
			allowedUsers: ['1'],
            mqtt: [
                 {
                    type: 'on',
                    set: '/devices/state_heating/controls/Отключена-Включена/on',
                    stat: '/devices/state_heating/controls/Отключена-Включена'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: true,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________hot_on_off______________// 
//_______________ELREBOOT______________//
       {
		   id: 'reset-001-sw',
           name: 'Перезагрузка',
           room: 'Серверная',
           type: 'devices.types.switch',
		   allowedUsers: ['1'],
		   
           mqtt: [
                 {
                    type: 'on',
                    set: '/devices/elswitch/controls/Перезагрузка/on',
                    stat: '/devices/elswitch/controls/Перезагрузка'
                },
            ],
            capabilities: [
                {
                    type: 'devices.capabilities.on_off',
                    retrievable: false,
                    state: {
                        instance: 'on',
                        value: true
                    }
                },
            ]
        },

//_______________ELREBOOT______________// 
		]
}
`

**Comment by lasthead0** [comment]
Так зе стоит смотреть в логи самого Яндекса, в навыке. Там тоже может быть что-то полезное.

**Comment by 1stat** [comment]
TypeError: Cannot read properties of undefined (reading 'log')
    at Device.setCapabilityState (/opt/yandex2mqtt/device.js:192:20)
    at module.exports.action (/opt/yandex2mqtt/routes/user.js:86:43)
    at Layer.handle [as handle_request] (/opt/yandex2mqtt/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/yandex2mqtt/node_modules/express/lib/router/route.js:144:13)
    at complete (/opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:453:5)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:272:22
    at /opt/yandex2mqtt/node_modules/passport/lib/http/request.js:52:7
TypeError: Cannot read properties of undefined (reading 'log')
    at Device.setCapabilityState (/opt/yandex2mqtt/device.js:192:20)
    at module.exports.action (/opt/yandex2mqtt/routes/user.js:86:43)
    at Layer.handle [as handle_request] (/opt/yandex2mqtt/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/yandex2mqtt/node_modules/express/lib/router/route.js:144:13)
    at complete (/opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:453:5)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:272:22
    at /opt/yandex2mqtt/node_modules/passport/lib/http/request.js:52:7

**Comment by 1stat** [comment]
Не подскажите куда копать?

**Comment by 1stat** [comment]
В яндексе пусто

**Comment by 1stat** [comment]
Разобрался. Только почему то свет только включаеться. Выключить не могу из алисы. Пример взял Вашей гостинной

**Comment by 1stat** [comment]
Разобрался, моя не внимательность. Конфиг не правильно заполнил. С wirenboard (пошивка 2307) работает исправно.

**Comment by 1stat** [comment]
+

**Comment by 1stat** [comment]
Разобрался, моя не внимательность. Конфиг не правильно заполнил. С wirenboard (пошивка 2307) работает исправно.
