### ISSUE TITLE
Не отображается/отправляется температура.

### ISSUE THREAD

**Issue by KostyanApa** [lasthead0/yandex2mqtt#4]
по температуре прилетает 0, влажность отдает без проблем.

```
  {
            id: 'lvr-001-weather',
            name: 'В гараже',
            room: 'Гараж',
            type: 'devices.types.sensor',
            allowedUsers: ['1'],
            mqtt: [
                {
                    instance: 'temperature',
                    state: '/mqtt/0/stat/weather01/temperature',
                },
                {
                    instance: 'humidity',
                    state: '/mqtt/0/stat/weather01/humidity',
                },
            ],
            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius',
                    },
                },
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'humidity',
                        unit: 'unit.percent',
                    },
                },
            ],
        },

```

**Comment by lasthead0** [comment]
Если при одинаковых настройках один параметр прилетает, а второй нет - проблема не в настройках и не в y2m.
С какой системой УД используется?

**Comment by bonuzzz** [comment]
`        {
            id: 'weather',
            name: 'Погода',
            room: 'Двор',
            type: 'devices.types.sensor',
            mqtt: [
                {
                    instance: 'temperature',
                    state: 'yandex/weather/temperature',
                },
                {
                    instance: 'humidity',
                    state: 'yandex/weather/humidity',
                },
            ],
            properties: [
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'temperature',
                        unit: 'unit.temperature.celsius',
                    },
                },
                {
                    type: 'devices.properties.float',
                    retrievable: true,
                    parameters: {
                        instance: 'humidity',
                        unit: 'unit.percent',
                    },
                },
            ],
        },`

решение для стабильной ветки. порядка двух месяцев работает без сбоев.

**Comment by pmaster555** [comment]
У меня тоже кстати все датчики отвалились. Обновил на бетку, тоже самое. нет датчиков

**Comment by pmaster555** [comment]
Добавил новый датчик, ни в какую не хочет брать температуру. Если сменить топик на какой нибудь старый, то работает, ставлю новый топик, показывает 0. Делаю в иоброкере. Объект и удалял и создавал, ничего не помогает. Как посмотреть что ему надо?

**Comment by bonuzzz** [comment]
@pmaster555 отправить значение в нужный топик, который в конфиге прописан. если напрямую в мктт посылать и яндекс подхватывает, то значит дело уже в иоброкер. я сам mqtt explorer пользуюсь, можно чем-то подобным.

**Comment by lasthead0** [comment]
Если в качестве УД используется ioBroker, то внимательно смотрим в объект, который "хранит" топик состояния (state) температуры , влажности и чего угодно. На вкладке RAW должно присутствовать нечто такое же (как ниже), что соответствует вашему топику
​"native": {
  "topic": "/yandex/controls/light_BdR_002/state"
}
Причём topic должен СТРОГО, ОДИН В ОДИН! соответствовать тому, что в конфиге y2m.
Важно!!! Если Вы изменили этот параметр в объекте, нужно перезапустить mqtt инстанс.
y2m в этой части работает чётко, 99% "багов" - это особенность работы именно УД.
